declare const util: any;
declare const replicators: any;
declare const ApiClient: any;
declare class Telegram extends ApiClient {
    getMe(): any;
    getFile(fileId: any): any;
    getFileLink(fileId: any): any;
    getUpdates(timeout: any, limit: any, offset: any, allowedUpdates: any): any;
    getWebhookInfo(): any;
    getGameHighScores(userId: any, inlineMessageId: any, chatId: any, messageId: any): any;
    setGameScore(userId: any, score: any, inlineMessageId: any, chatId: any, messageId: any, editMessage: boolean, force: any): any;
    setWebhook(url: any, cert: any, maxConnections: any, allowedUpdates: any): any;
    deleteWebhook(): any;
    sendMessage(chatId: any, text: any, extra: any): any;
    forwardMessage(chatId: any, fromChatId: any, messageId: any, extra: any): any;
    sendChatAction(chatId: any, action: any): any;
    getUserProfilePhotos(userId: any, offset: any, limit: any): any;
    sendLocation(chatId: any, latitude: any, longitude: any, extra: any): any;
    sendVenue(chatId: any, latitude: any, longitude: any, title: any, address: any, extra: any): any;
    sendInvoice(chatId: any, invoice: any, extra: any): any;
    sendContact(chatId: any, phoneNumber: any, firstName: any, extra: any): any;
    sendPhoto(chatId: any, photo: any, extra: any): any;
    sendDocument(chatId: any, doc: any, extra: any): any;
    sendAudio(chatId: any, audio: any, extra: any): any;
    sendSticker(chatId: any, sticker: any, extra: any): any;
    sendVideo(chatId: any, video: any, extra: any): any;
    sendVideoNote(chatId: any, videoNote: any, extra: any): any;
    sendVoice(chatId: any, voice: any, extra: any): any;
    sendGame(chatId: any, gameName: any, extra: any): any;
    sendMediaGroup(chatId: any, media: any, extra: any): any;
    getChat(chatId: any): any;
    getChatAdministrators(chatId: any): any;
    getChatMember(chatId: any, userId: any): any;
    getChatMembersCount(chatId: any): any;
    answerInlineQuery(inlineQueryId: any, results: any, extra: any): any;
    kickChatMember(chatId: any, userId: any, untilDate: any): any;
    promoteChatMember(chatId: any, userId: any, extra: any): any;
    restrictChatMember(chatId: any, userId: any, extra: any): any;
    exportChatInviteLink(chatId: any): any;
    setChatPhoto(chatId: any, photo: any): any;
    deleteChatPhoto(chatId: any): any;
    setChatTitle(chatId: any, title: any): any;
    setChatDescription(chatId: any, description: any): any;
    pinChatMessage(chatId: any, messageId: any, extra: any): any;
    unpinChatMessage(chatId: any): any;
    leaveChat(chatId: any): any;
    unbanChatMember(chatId: any, userId: any): any;
    answerCallbackQuery(callbackQueryId: any, text: any, url: any, showAlert: any, cacheTime: any): any;
    answerCbQuery(callbackQueryId: any, text: any, showAlert: any, extra: any): any;
    answerGameQuery(callbackQueryId: any, url: any): any;
    answerShippingQuery(shippingQueryId: any, ok: any, shippingOptions: any, errorMessage: any): any;
    answerPreCheckoutQuery(preCheckoutQueryId: any, ok: any, errorMessage: any): any;
    editMessageText(chatId: any, messageId: any, inlineMessageId: any, text: any, extra: any): any;
    editMessageCaption(chatId: any, messageId: any, inlineMessageId: any, caption: any, markup: any): any;
    editMessageReplyMarkup(chatId: any, messageId: any, inlineMessageId: any, markup: any): any;
    editMessageLiveLocation(latitude: any, longitude: any, chatId: any, messageId: any, inlineMessageId: any, markup: any): any;
    stopMessageLiveLocation(chatId: any, messageId: any, inlineMessageId: any, markup: any): any;
    deleteMessage(chatId: any, messageId: any): any;
    setChatStickerSet(chatId: any, setName: any): any;
    deleteChatStickerSet(chatId: any): any;
    getStickerSet(setName: any): any;
    uploadStickerFile(ownerId: any, stickerFile: any): any;
    createNewStickerSet(ownerId: any, name: any, title: any, stickerData: any): any;
    addStickerToSet(ownerId: any, name: any, stickerData: any, isMasks: any): any;
    setStickerPositionInSet(sticker: any, position: any): any;
    deleteStickerFromSet(sticker: any): any;
    sendCopy(chatId: any, message: any, extra: any): any;
}
